### ISSUE TITLE
README file

### ISSUE THREAD

**Issue by max-little** [max-little/GRAPL#7]
We'll try to keep the revision notes short: the aim is to have an accessible list of only the most significant changes to the latest release version.

**Comment by Nikoleta-v3** [comment]
👍🏻 not an issue at all. I find release notes useful. My comment was to keep in mind that the list could get longer and longer. 

fyi there is a nice way of automatically generating release notes with new tags release: https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes. Maybe it's something you would like to implement in the future.

**Comment by max-little** [comment]
Thanks Nikoleta!

**Comment by max-little** [comment]
Closed.
